Updates script

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -29,53 +29,35 @@ jobs:
         run: yarn install
       - name: Validate Release Is Needed
         run: |
-      - name: Bump Release Version
-        id: version
-        run: |
-          yarn bump-version
-          RELEASE_VERSION=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)
-          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT
-          if test -f ./.changes/${{ steps.version.outputs.RELEASE_VERSION }}.md
+          if [ -n "$(ls .changes/unreleased 2>/dev/null)" ]
           then
-            echo "No valid release found for . stage 2 will not run."
-            exit 1
+            echo "Changes detected. Creating a new release."
           else
-            echo "New release created."
+            echo "No changes detected. Aborting release process."
+            exit 1
           fi
-          git add .
-          git commit -m "Cut Release '${{ steps.version.outputs.RELEASE_VERSION }}'"
-      - name: Ensure Release Does Not Exist
+      - name: Bump release version
+        id: version
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          gh release delete ${{ steps.version.outputs.RELEASE_VERSION }} || true
-      - name: Ensure Changelog
-        run: |
           git config user.name "OpsLevel Bots"
           git config user.email "bots@opslevel.com"
-          if test -f ./.changes/${{ steps.version.outputs.RELEASE_VERSION }}.md
-          then
-            echo "Skip Changie..."
-          else
-            go install github.com/miniscruff/changie@latest
-            changie batch ${{ steps.version.outputs.RELEASE_VERSION }}
-            changie merge
-            git add .
-            git commit -m "Cut Release '${{ steps.version.outputs.RELEASE_VERSION }}'"
-            git push origin HEAD
-          fi
-          git tag -f ${{ steps.version.outputs.RELEASE_VERSION }} -m "Cut Release '${{ steps.version.outputs.RELEASE_VERSION }}'"
-          git push -f origin refs/tags/${{ steps.version.outputs.RELEASE_VERSION }}
-      # - name: Run GoReleaser
-      #   uses: goreleaser/goreleaser-action@v5.0.0
-      #   with:
-      #     args: release --rm-dist --release-notes=../.changes/${{ steps.version.outputs.RELEASE_VERSION }}.md
-      #     workdir: ./src
-      #   env:
-      #     GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
-      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #     ORG_GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_TOKEN }}
-      - name: Report Release To OpsLevel
+          yarn bump-version
+          RELEASE_VERSION=$(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)
+          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_OUTPUT
+          git add .
+          git commit -m "Cut Release '$RELEASE_VERSION'"
+          git push origin HEAD
+          gh release delete $RELEASE_VERSION || true
+          git tag -f v$RELEASE_VERSION -m "Cut Release 'v$RELEASE_VERSION'"
+          git push -f origin refs/tags/v$RELEASE_VERSION 
+      - name: Release to npm
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+        run: |
+          npm publish
+      - name: Report release to opsLevel
         uses: opslevel/report-deploy-github-action@v0.7.0
         with:
           integration_url: ${{ secrets.DEPLOY_INTEGRATION_URL }}
